#spring:
#  cloud:
#    gateway:
#      httpclient:
#        pool:
#          maxIdleTime: 20000
#      globalcors:
#        cors-configurations:
#          '[/**]': # 匹配所有请求
#            allowedOrigins: "*" # 跨域处理 允许所有域
#            allowedMethods: # 支持的方法
#              - GET
#              - POST
#      routes:
#        - id: user
#          uri: lb://cyber-steam-music-user
#          predicates:
#            - Path=/user/**
#          filters:
#            - StripPrefix=1
#        - id: music
#          uri: lb://cyber-steam-music-music
#          predicates:
#            - Path=/music/**
#          filters:
#            - StripPrefix=1